---
title: "Writing and Reanalysis"
output: html_document
---




# **Summary:**
Janntaul Kawnine
Psych Statistics 3400 Honors
Professor Crump
When Delays Improve Memory: Stabilizing Memory in Children May Require Time
Kevin P. Darby, Vladimir M. Sloutsky

Part 1: Summary of the paper

	In a recently published scientific paper by Ohio State University revealed about the retroactive interference among children. Retroactive interference is when learning new things reduces memory for older information. Memory is an important aspect of our life because the retention of information guides us to plan for works and help us decide regarding different subject matter and problems. Unfortunately, it is hard to retain all the information and have clear memory of different actions due to proactive and retroactive interference. Proactive interference is when people’s old memory interferes with learning new things and as mentioned earlier, retroactive memory is forgetting old memory due to new information. Therefore, the authors are set to study the memory and cognitive development in children and design a study with the hypothesis of whether delay is required to stabilize the information retained by our hippocampus and improves the memory among children. The experimental result reveals that retroactive among children is catastrophic in children and it is worse than adults. The retroactive interference effect among adults is studied in a different research done by the same author which has similar effect as the children but the effect is less severe. In this particular study, the author only focuses on children with mean age of 5.2.
	
	The study is separated into two different experiments. In experiment 1, the authors study the catastrophic interference in children on consolidation over time and in the next experiment, the authors study the effect of the consolidation formation and how the information is presented. In both experiments, children learned connection between pairs of objects in two conditions (delay condition and no delay condition) and an outcome (cartoon character). There are overlapping pairs and unique pairs. The overlapping pair has elements from different phases combined and the unique pair has elements only specific and constant to the phase only. The no delay condition has 1minute break across different phases and the delay condition has 1minute break between phase 1 and 2 and 48 hours break between phase 2 and 3. Therefore, the phases, pair types (unique and overlapping pairs), blocks (1-5), experimental conditions (delay and no delay) are all independent variables conditions and the accuracy of the name of cartoon character is the dependent variable. 
	
	Results in no delay condition shows significant retroactive interference using the 2(phase: 1 vs. 3) × 2 (pair type: overlapping vs. unique) repeated measure ANOVA. The ANOVA shows that F(1, 24) = 13.04, p = .001, ηp2 = .35. As the p value is less than .001, it shows the authors reject the null hypothesis and believe that the difference of accuracy between the pair types and phases are due to retroactive effects.  For the delay condition, there is a similar ANOVA test which shows that p=.20 meaning retaining the null which notes that the difference between the accuracy across phases and pair types are due to non-retroactive effects. The interaction for the phase and pair types using ANOVA shows that F(1, 28) = 4.24, p = .049, ηp2 = .13 showing retroactive difference between the phases and blocks. Paired t test also shows that accuracy decreases for overlapping than the unique pair. 

	The experiment revealed that having the 48 hours delay between phases during the overlapping pairs improved the memory of the children and eliminated the catastrophic interference. When there was no delay, children experienced significant catastrophic retroactive interference effects. The result showed that if there is a delay between learning and testing, then children’s brain retains the information more and have a lasting memory of the incidents. Also, the other important aspect of the result is that the independent variable (pairs of objects) has to be connected to each other so that children can conform the pairs into a single coherent thing. Therefore, both delay and overlapping elements are necessary to eliminate the effect of retroactive interference. 
	
	There are few theories related to why the children failed to form memory traces for no delay. For example, it is possible that children have interference due to immaturity of the hippocampus. Also, they may have difficulty binding information in memory at the age as found by another research study. Also, it is possible that hippocampus-dependent activities are sensitive to time due to relationship between consolidation and task performance.Even though the study doesn’t really find a direct correction between the retroactive interference, consolidation, and generalization, the study definitely sheds more light to understand the memory and cognitive development at an early stage of human development. 

# **Reanalysis:**

Part 2: Reanalysis of one of the ANOVA calculations:

	As part of the reanalysis part, I have tried to analyzed the 2 (phase: 1 vs. 3) × 2 (pair type: overlap- ping vs. unique) repeated measures analysis of variance (ANOVA) with the help of the professor. The authors calculation of the 2*2 ANOVA was F(1, 24) = 13.04, p = .001, ηp2 = .35. Due to some error, we were unable to find the exact match of the F value and the p value. Our F(1,24)=11.36, p=.0025 However, our conclusion was consistent to the conclusion of the author as the p values were smaller than .05. As a result, both reanalysis’ and authors’ conclusion stated that there was substantial retroactive interference between the phases and pair types in the no delay condition. Also, there was another bar graph which shows that mean accuracies across pair types and phases for no delay conditions. The bar graph shows that accuracy attenuated for overlapping for phase 1 and 2 but increased for phase 2 and 3 for overlapping pairs. On the other hand, the accuracy increased across all the phases for the unique pairs. 
	
	There was another reanalysis done to clarify that our calculation for the first one was not due to wrong R code or any other problem. I did reanalysis for the direct relationship for the delay and no delay using a three-way ANOVA analysis. I performed mixed ANOVA with phase (1 vs. 3) and pair type (overlapping vs. unique) as within-subject factors and condition (no delay vs. delay) as a between-subjects factor. My reanalysis of the ANOVA table showed that F(1, 48) = 6.19, p = .016. On the other hand, the authors’ ANOVA result showed that F (1, 48) = 12.84, p = .001, ηp2 = .21. As seen my result was not same as the authors’ result, there might be some problem with the data. Also, it was possible that the authors’ miscalculated their samples of data. Ultimately, it was important to understand that the p value was smaller than .05. It showed that there was less retroactive interference in the delay condition than no-delay condition. 

